# ─── Telegram Bot ───────────────────────────────────────────
TELEGRAM_BOT_TOKEN="613594704:AAGIgoPgUdIqX7v4tS8VHPdr2ewzNhsrrBQ"
TELEGRAM_CHAT_ID="-1001491708403"

# ─── Database ───────────────────────────────────────────────
DB_USER="root"
DB_PASS="@Yahoo212" # Silakan isi password MySQL Anda di sini
